name: Build all codes
on:
  push:

jobs:
  build-all-codes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build code
        run: |
          make build


